---
- name: Configure etcd cluster
  hosts: etcd
  become: true
  roles:
    - role: etcd
      tags: [ etcd ]

- name: Configure master cluster
  hosts: master
  become: true
  roles:
    - role: k8s
      tags: [k8s]

- name: create
